[package]
name = "gredit-mcp"
version = "0.1.0"
edition = "2024"
publish = false

[dependencies]
anyhow = "1"
nu-cmd-lang = { version = "0.115.1" }
nu-command = { version = "0.115.1", default-features = false, features = ["os"] }
nu-engine = { version = "0.115.1", default-features = false, features = ["os"] }
nu-parser = { version = "0.115.1", default-features = false }
nu-protocol = { version = "0.115.1", default-features = false, features = ["os"] }
rmcp = { version = "3.4", features = ["elicitation", "server", "macros", "transport-io", "schemars"] }
schemars = "1"
serde = { version = "1", features = ["derive"] }
tokio = { version = "1", features = ["io-util", "macros", "process", "rt-multi-thread", "time"] }
regex = "1"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }

[dev-dependencies]
tempfile = "3"

[profile.release]
opt-level = 3
lto = "fat"
codegen-units = 1
panic = "abort"
strip = "symbols"
